<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sawyer_camera_plate">
  <xacro:macro name="sawyer_camera_plate" params="side gazebo">
  <xacro:property name="sawyer_camera_plate_length" value="0.010" scope="global"/>
  <link name="${side}_camera_plate_base">
    <inertial>
      <origin xyz="-0.01738 0.0 0.01923" rpy="0 0 0" />
      <mass value="0.09291" />
      <inertia ixx="0.000061"  ixy="0.0"  ixz="-0.000019"
               iyy="0.000067"  iyz="0.0" izz="0.000068" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://sawyer_camera_plate/meshes/camera_plate.STL" />
      </geometry>
      <material name="black">
        <color rgba="0.05 0.05 0.05 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.0135" rpy="0 0 0" />
        <geometry>
          <cylinder length="${sawyer_camera_plate_length}" radius="0.04"/>
        </geometry>
        <material name="black">
          <color rgba="0.05 0.05 0.05 1"/>
        </material>
    </collision>
  </link>
  <xacro:if value="${gazebo}">
    <gazebo reference="${side}_camera_plate_base">
      <material>Gazebo/FlatBlack</material>
    </gazebo>
  </xacro:if>
  <link name="${side}_camera_plate_robot_mount" />
  <joint name="${side}_camera_plate_mount_joint" type="fixed">
    <origin xyz="0 0 ${sawyer_camera_plate_length+0.0025}" rpy="0 0 0" />
    <parent link="${side}_camera_plate_base"  />
    <child  link="${side}_camera_plate_robot_mount" />
  </joint>

  <link name="${side}_camera_plate_cam_mount" />
  <joint name="${side}_camera_plate_cam_joint" type="fixed">
    <origin xyz="-0.0395  0.0 0.040" rpy="${-pi/2} 0 ${pi/2}" />
    <parent link="${side}_camera_plate_base"  />
    <child  link="${side}_camera_plate_cam_mount" />
  </joint>


  <link name="astra_camera">
    <inertial>
      <origin xyz="0.0 -0.0013 0.02929" rpy="0 0 0" />
      <mass value="0.22045" />
      <inertia ixx="0.000074"  ixy="0.0"  ixz="0.0"
               iyy="0.00043"  iyz="-0.000009" izz="0.000429" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://sawyer_camera_plate/meshes/astra.stl" />
      </geometry>
      <material name="black">
        <color rgba="0.05 0.05 0.05 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0.01 0.025" rpy="0 0 0" />
        <geometry>
          <box size="0.180 0.070 0.050"/>
        </geometry>
        <material name="black">
          <color rgba="0.05 0.05 0.05 1"/>
        </material>
    </collision>
  </link>
  <xacro:if value="${gazebo}">
    <gazebo reference="${side}_camera_astra_base">
      <material>Gazebo/FlatBlack</material>
    </gazebo>
  </xacro:if>

  </xacro:macro>
</robot>
